# Generated by Django 3.1.2 on 2020-10-21 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 21, 8, 16, 58, 994316)),
        ),
    ]
