# Generated by Django 3.1.2 on 2020-10-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201026_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
